server:
  port: 8000

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.68.63:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhyf123456++

  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.56.1:8848
  application:
    name: gulimall-member

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto



#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql、mongodb】


