spring:
  cloud:
    alicloud:
      access-key: LTAI4GKEqs7HSk2pkKuNC951
      secret-key: SX0V5ehY1mLDq60ka7ZzlU2qOUSg1W
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimallzhyf
    nacos:
      discovery:
        server-addr: http://192.168.56.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000